# kickstart travis.
language: java
jdk:
  - oraclejdk8
  - oraclejdk7
script: ant  -f /home/travis/build/eNcoRe101/BDLG-3rdYearProject -Dnb.internal.action.name=test -Dignore.failing.tests=true -Dnb.wait.for.caches=true test